### ISSUE TITLE
List of units inferred from an Arbiter includes Fleet Beacon (incorrectly) and excludes Arbiter Tribunal

### ISSUE THREAD

**Issue by dgant** [Games-and-Simulations/bwom#1]
https://github.com/Games-and-Simulations/bwom/blob/d74c24722c10b5984ae8ac9c36831d22e6eaa8af/OpponentModelling/source/ProtossPlayer.cpp#L108

**Comment by dgant** [comment]
Also needs Citadel of Adun

**Comment by bohusto1** [comment]
Thank you for the notice! The proper inherenced buildings were missed at more places. I added them and also fixed the addUnit method when adding inferenced unit.
